### ISSUE TITLE
dipy_reconst_dti failing

### ISSUE THREAD

**Issue by soichih** [brain-life/app-dipy-workflows#3]
@skoudoro I am seeing following error message when I try to run dipy_reconst_dti

```
INFO:Computing DTI metrics for ../5a79de2c8e2185002a44906a/59b9ac03620ac10cb3e05d2c/dwi.nii.gz
INFO:Tensor estimation...
Traceback (most recent call last):
  File "/usr/local/bin/dipy_reconst_dti", line 9, in <module>
    run_flow(ReconstDtiFlow())
  File "/usr/local/lib/python2.7/dist-packages/dipy/workflows/flow_runner.py", line 80, in run_flow
    return flow.run(**args)
  File "/usr/local/lib/python2.7/dist-packages/dipy/workflows/reconst.py", line 106, in run
    b0_threshold)
  File "/usr/local/lib/python2.7/dist-packages/dipy/workflows/reconst.py", line 175, in get_fitted_tensor
    bvals, bvecs = read_bvals_bvecs(bval, bvec)
  File "/usr/local/lib/python2.7/dist-packages/dipy/io/gradients.py", line 41, in read_bvals_bvecs
    vals.append(np.squeeze(np.loadtxt(this_fname)))
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1024, in loadtxt
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 725, in floatconv
    return float(x)
ValueError: invalid literal for float(): 0,1000,1000,1000,1000,1000,0,1000,1000,1000,1000,1000,0,1000,1000,1000,1000,1000,0,1000,1000,1000,1000,1000,0,1000,1000,1000,1000,1000,0,1000,1000,1000,1000,1000,0,1000,1000,1000,1000,1000,0,1000,1000
```

I am guessing it's not liking the bvals format (not space delimited?) Some bvals are space delimited, and some are comma delimited (old ones?), I've also seen ones that are TAB delimited, I think. 

If this is indeed caused by the delimiter issue, is there any chance dipy can be made to handle both white space and comma delimited bvals?

**Comment by skoudoro** [comment]
Indeed, we use [this function](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.loadtxt.html) for loading `bvals` en `bvects`.
We need a way to detect the delimiter before loading.

But I wonder if it is not better to create an app for Normalizing `bval / bvects`  files ? Which software use comma delimited bvals ? any idea ?

**Comment by soichih** [comment]
If I remember correctly, it was actually one of our own app that was generating comma delimited bvals. 
> https://github.com/brain-life/app-splitshells/issues/8

I think we've been good at sticking with fsl format (space delimited) since then, but I think comma delimited bvecs/bvals could be used by other groups??

Another issue is that, the datasets currently stored in Brainlife archive could contain comma delimited bvals - especially if it's an old datasets, and user could take those datasets and send it to any apps. App that parses bvecs/bvals just needs to replace all "," with " " before splitting into values (if it's already space delimited, then it's a null operation) to handle such datasets.

If this can't be done at dipy level, we can add the replace command on the main script, but then we will have to do this on all dipy apps.

**Comment by skoudoro** [comment]
- I created an issue on DIPY for that so it will be done (I hope before the release).
- How do you manage this problem with FSL app?

**Comment by skoudoro** [comment]
As you can see [here](https://github.com/nipy/dipy/pull/1422/files) @soichih, a new contributor fix this issue. It will be in for the next release.

**Comment by soichih** [comment]
Great! When will this be released?

**Comment by skoudoro** [comment]
A week after resolving [this issue](https://github.com/nipy/dipy/issues/1435).  So 2 weeks, I hope :-)
