### ISSUE TITLE
Update output datatype to use the new neuro/tensor datatype

### ISSUE THREAD

**Issue by soichih** [brain-life/app-dipy-workflows#4]
We've created a new datatype called "neuro/tensor" that can be used to store tensor scalar images (fa.nii.gz, md.nii.gz, rd.nii.gz, and ad.nii.gz) To promote the interoperability, we should update the BL app registration for dipy_reconst_dti to use this new datatype.

**Comment by skoudoro** [comment]
Nice ! good to know that! 

Should we update the app now ? is it already available ?

**Comment by soichih** [comment]
Yes, you can update it now > https://brainlife.io/warehouse/app/5a51582ae062630027709ceb

But, neuro/tensor only has those 4 files (fa.nii.gz, md.nii.gz, rd.nii.gz, and ad.nii.gz) listed. I think reconst pipeline produces a few more files - I can list them on neuro/tensor as "optional" files so that those files will be picked up.

**Comment by skoudoro** [comment]
+1 for adding the others files as "optional"

I just made the app update, you can close this issue
